"""
A.R.G.U.S. — Decision Relational Model
Persists the final operational policy action (APPROVE, REVIEW, BLOCK)
and explainable forensic reasons.
"""

import uuid
from datetime import datetime, timezone
from typing import List
from sqlalchemy import String, DateTime, ForeignKey, Uuid, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from ..base import Base


class DecisionRecord(Base):
    """
    Operational decision generated by the policy decision layer.
    Links directly to the corresponding Risk Assessment and stores
    observable diagnostic reasons.
    """
    __tablename__ = "decisions"

    decision_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, primary_key=True, default=uuid.uuid4
    )
    assessment_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("risk_assessments.assessment_id", ondelete="CASCADE"), unique=True, nullable=False, index=True
    )
    policy_decision: Mapped[str] = mapped_column(
        String(16), nullable=False, index=True
    )  # APPROVE, REVIEW, BLOCK
    reasons: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )

    # Relationships
    risk_assessment: Mapped["RiskAssessmentRecord"] = relationship(
        "RiskAssessmentRecord", back_populates="decision"
    )

    def __repr__(self) -> str:
        return f"<DecisionRecord(decision_id={self.decision_id}, policy='{self.policy_decision}')>"
